DormitoryWebProject/Controllers/Welcome/LienheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers
{
    public class LienheController : Controller
    {
        // GET: Lienhe
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Datcho()
        {
            return View("Datcho");
        }
    }
}

DormitoryWebProject/Controllers/Welcome/SukienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers
{
    public class SukienController : Controller
    {
        // GET: Sukien
        public ActionResult Index()
        {
            return View();
        }
    }
}

DormitoryWebProject/Views/Shared/PartialViews/WelcomePartial/_WelcomeCopyright.cshtml
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 text-center">
        <hr style="border-color: #004c56; opacity: 0.4;">
        <h5 class="visible-lg visible-md">Copyright &copy 2020 KTX Web Development Team. All Rights Reserved</h5>
        <h6 class="visible-sm"><small>Copyright &copy 2020 KTX Web Development Team. All Rights Reserved</small></h6>
        <p class="visible-xs"><small>Copyright &copy 2020 KTX Web Development Team. All Rights Reserved</small></p>
    </div>
</div>

DormitoryWebProject/Views/Shared/PartialViews/WelcomePartial/_WelcomeKTXAddress.cshtml
<div class="row">

    <div class="col-lg-3 col-md-10 col-sm-10 col-xs-10 pull-left logo-section">
        <img class="img-responsive f-img-custom" src="~/assets/images/Logo-ngang.png">
    </div>

    <div class="col-lg-3 visible-lg">
        <h5 class="title">KTX 135A</h5>
        <p>
            Địa chỉ: 135A Trần Hưng Đạo, P.Cầu Ông Lãnh, Q.1, TP.HCM <br>
            Điện thoại: 02838368334
        </p>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12 text-center hidden-lg">
        <h4 class="visible-sm title">KTX 135A</h4>
        <h3 class="visible-md title">KTX 135A</h3>
        <h6 class="visible-xs title">KTX 135A</h6>
        <p>
            Địa chỉ: 135A Trần Hưng Đạo, P.Cầu Ông Lãnh, Q.1, TP.HCM <br>
            Điện thoại: 02838368334
        </p>
    </div>

    <div class="col-lg-3 visible-lg">
        <h5 class="title">KTX 43 - 45</h5>
        <p>
            Địa chỉ: 43 - 45 Nguyễn Chí Thanh, P.9, Q.5, TP.HCM<br>
            Điện thoại: 02838359359
        </p>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12 text-center hidden-lg">
        <h4 class="visible-sm title">KTX 43 - 45</h4>
        <h3 class="visible-md title">KTX 43 - 45</h3>
        <h6 class="visible-xs title">KTX 43 - 45</h6>
        <p>
            Địa chỉ: 43 - 45 Nguyễn Chí Thanh, P.9, Q.5, TP.HCM<br>
            Điện thoại: 02838359359
        </p>
    </div>

    <div class="col-lg-3 visible-lg">
        <h5 class="title">BỘ PHẬN HỖ TRỢ SINH VIÊN</h5>
        <p>
            Địa chỉ: B.014 - 279 Nguyễn Tri Phương, Phường 5, Quận 10, TPHCM<br>
            Điện thoại: 02838551777 - 02838573533 <br>
            Email: <a id="email-link" href="mailto:trungtamhotrosinhvien@ueh.edu.vn">trungtamhotrosinhvien@ueh.edu.vn</a>
        </p>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12 text-center hidden-lg">
        <h4 class="visible-sm title">BỘ PHẬN HỖ TRỢ SINH VIÊN</h4>
        <h3 class="visible-md title">BỘ PHẬN HỖ TRỢ SINH VIÊN</h3>
        <h6 class="visible-xs title">BỘ PHẬN HỖ TRỢ SINH VIÊN</h6>
        <p>
            Địa chỉ: B.014 - 279 Nguyễn Tri Phương, Phường 5, Quận 10, TPHCM<br>
            Điện thoại: 02838551777 - 02838573533 <br>
            Email: <a id="email-link" href="mailto:trungtamhotrosinhvien@ueh.edu.vn">trungtamhotrosinhvien@ueh.edu.vn</a>
        </p>
    </div>

</div>

DormitoryWebProject/Views/Shared/PartialViews/WelcomePartial/_WelcomeNorNavFixed.cshtml
<header id="normal-header">
    <div class="my-menu-icon">
        <a href="javascript:void(0);" onclick="openMENU()"><i class="fa fa-bars"></i></a>
    </div>
    <div class="my-logo-section-wrap active">
        <a href="@Url.Action("Index","Trangchu")"><img id="ueh-logo" src="~/assets/images/Logo.png" alt="UEH KTX Logo"></a>
    </div>
    <nav class="my-nor-nav">
        <ul class="clearfix">
            <li><a href="@Url.Action("Index","Trangchu")" data-content="TRANG CHỦ">TRANG CHỦ</a></li>
            <li><a href="@Url.Action("Index","Sukien")" data-content="SỰ KIỆN">SỰ KIỆN</a></li>
            <li><a href="@Url.Action("Index","Lienhe")" data-content="LIÊN HỆ">LIÊN HỆ</a></li>
        </ul>
        <button id="login-bt" onclick="location.href='@Url.Action("Login","Account")'">ĐĂNG NHẬP</button>
    </nav>
</header>

DormitoryWebProject/Views/Shared/PartialViews/WelcomePartial/_WelcomeNorNavScroll.cshtml
<header id="hide-onscroll">
    <div class="my-menu-icon">
        <a href="javascript:void(0);" onclick="openMENU()"><i class="fa fa-bars"></i></a>
    </div>
    <div class="my-logo-section-wrap active">
        <a href="@Url.Action("Index","Trangchu")"><img id="ueh-logo" src="~/assets/images/Logo.png" alt="UEH KTX Logo"></a>
    </div>
    <nav class="my-nor-nav">
        <ul class="clearfix">
            <li><a href="@Url.Action("Index","Trangchu")" data-content="TRANG CHỦ">TRANG CHỦ</a></li>
            <li><a href="@Url.Action("Index","Sukien")" data-content="SỰ KIỆN">SỰ KIỆN</a></li>
            <li><a href="@Url.Action("Index","Lienhe")" data-content="LIÊN HỆ">LIÊN HỆ</a></li>
        </ul>
        <button id="login-bt" onclick="location.href='@Url.Action("Login","Account")'">ĐĂNG NHẬP</button>
    </nav>
</header>

DormitoryWebProject/Views/Shared/PartialViews/WelcomePartial/_WelcomeSocialLinks.cshtml
<div class="row text-center">
    <p class="social-links">
        <a href="https://www.facebook.com/TTHTSV.UEH" target="_blank"><img id="facebook-icon" src="~/assets/images/facebook-icon.png" alt="Facebook"></a>
        <a href="#"><img id="Twitter-icon" src="~/assets/images/Twitter-icon.png" alt="Twitter"></a>
        <a href="#"><img id="instagram-icon" src="~/assets/images/instagram-icon.png" alt="Instagram"></a>
    </p>
</div>