DormitoryWebProject/Controllers/CMS/CMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers.CMS
{
    public class CMSController : Controller
    {
        // GET: CMS
        public ActionResult Index()
        {
            ViewData["aCMS"] = "active";
            return View("CMSHome");
        }
    }
}

DormitoryWebProject/Controllers/Home/HoadonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers
{
    [RoutePrefix("Home/Hoadon")]
    public class HoadonController : Controller
    {
        //GET: Home/Hoadon/Hoadonlephi
        public ActionResult Hoadonlephi()
        {
            ViewData["aHD"] = "active";
            ViewData["aHDLP"] = "active";
            return View();
        }

        //GET: Home/Hoadon/Hoadondiennuoc
        public ActionResult Hoadondiennuoc()
        {
            ViewData["aHD"] = "active";
            ViewData["aHDDN"] = "active";
            return View();
        }
    }
}

DormitoryWebProject/Controllers/Home/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers
{
    [RoutePrefix("Home/Nguoidung")]
    public class NguoidungController : Controller
    {
        // GET: Home/Nguoidung/Quanlynguoidung
        [Route("Thongtinnguoidung")]
        public ActionResult Thongtinnguoidung()
        {
            ViewData["aND"] = "active";
            ViewData["aTTND"] = "active";
            return View();
        }

        // GET: Home/Nguoidung/Quanlynguoidung
        [Route("Quanlynguoidung")]
        public ActionResult Quanlynguoidung()
        {
            ViewData["aND"] = "active";
            ViewData["aQLND"] = "active";
            return View();
        }

        // GET: Home/Nguoidung/Themnguoidung
        [Route("Themnguoidung")]
        public ActionResult Themnguoidung()
        {
            ViewData["aND"] = "active";
            ViewData["aQLND"] = "active";
            return View();
        }

        // GET: Home/Nguoidung/Quanlynhomnguoidung
        [Route("Quanlynhomnguoidung")]
        public ActionResult Quanlynhomnguoidung()
        {
            ViewData["aND"] = "active";
            ViewData["aQLNND"] = "active";
            return View();
        }

        // GET: Home/Nguoidung/Themnhomnguoidung
        [Route("Themnhomnguoidung")]
        public ActionResult Themnhomnguoidung()
        {
            ViewData["aND"] = "active";
            ViewData["aQLNND"] = "active";
            return View();
        }
    }
}

DormitoryWebProject/Controllers/Home/SinhvienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers
{
    [RoutePrefix("Home/Sinhvien")]
    public class SinhvienController : Controller
    {
        //GET: Home/Sinhvien/Timhososinhvien
        [Route("Timhososinhvien")]
        public ActionResult Timhososinhvien()
        {
            ViewData["aSV"] = "active";
            ViewData["aTHSSV"] = "active";
            return View();
        }

        //GET: Home/Sinhvien/Thongtinsinhvien
        [Route("Thongtinsinhvien")]
        public ActionResult Thongtinsinhvien()
        {
            ViewData["aSV"] = "active";
            ViewData["aTHSSV"] = "active";
            return View();
        }

        //GET: Home/Sinhvien/Themsinhvien
        [Route("Themsinhvien")]
        public ActionResult Themsinhvien()
        {
            ViewData["aSV"] = "active";
            ViewData["aTSV"] = "active";
            return View();
        }

        //GET: Home/Sinhvien/Downloaddanhsach
        [Route("Downloaddanhsach")]
        public ActionResult Downloaddanhsach()
        {
            ViewData["aSV"] = "active";
            ViewData["aDDS"] = "active";
            return View();
        }
    }
}

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeNavbarMessage.cshtml
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
            <!-- Message Start  -->
            <div class="media">
                <img src="~/assets/images/dashboard/user7-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                        Brad Diesel
                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">Call me whenever you can...</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
            </div>
            <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <!-- Message Start  -->
            <div class="media">
                <img src="~/assets/images/dashboard/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                        John Pierce
                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">I got your message bro</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
            </div>
            <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
                <img src="~/assets/images/dashboard/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                        Nora Silvester
                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">The subject goes here</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
            </div>
            <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
    </div>
</li>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeNavbarNotification.cshtml
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
    </div>
</li>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeNavbarSearch.cshtml
<form class="form-inline" id="formsearch">
    <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Tìm kiếm" aria-label="Tìm kiếm">
    </div>
</form>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeSidebarBrandLogo.cshtml
<a href="@Url.Action("Dashboard","Home")" class="brand-link">
    <img src="~/assets/images/logo-1.png" alt="UEH Logo" class="brand-image" id="hinhlogo">
    <span class="brand-text text-lg">UEH DORMITORY</span>
</a>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeSidebarMenu.cshtml
<nav class="mt-2 accent-yellow">
    <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent nav-flat nav-collapse-hide-child" data-widget="treeview" role="menu" data-accordion="true" data-animation-speed="200">
        <!-- Dasboard -->
        <li class="nav-item">
            <a href="@Url.Action("Dashboard","Dashboard")" class="nav-link @ViewData["aDB"]">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                </p>
            </a>
        </li>

        <!-- Người dùng -->
        <li class="nav-item">
            <a href="#" class="nav-link @ViewData["aND"]">
                <i class="nav-icon fas fa-user"></i>
                <p>
                    <i class="right fas fa-angle-left"></i>
                    Người dùng
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("Thongtinnguoidung","Nguoidung")" class="nav-link @ViewData["aTTND"]">
                        <p>Thông tin người dùng</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Quanlynguoidung","Nguoidung")" class="nav-link @ViewData["aQLND"]">
                        <p>Quản lý người dùng</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Quanlynhomnguoidung","Nguoidung")" class="nav-link @ViewData["aQLNND"]">
                        <p>Quản lý nhóm người dùng</p>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Sinh viên -->
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link @ViewData["aSV"]">
                <i class="nav-icon fas fa-users"></i>
                <p>
                    Sinh Viên
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("Timhososinhvien","Sinhvien")" class="nav-link @ViewData["aTHSSV"]">
                        <p>Tìm hồ sơ sinh viên</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Themsinhvien","Sinhvien")" class="nav-link @ViewData["aTSV"]">
                        <p>Thêm sinh viên</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Downloaddanhsach","Sinhvien")" class="nav-link @ViewData["aDDS"]">
                        <p>Download danh sách</p>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Khu/phong -->
        <li class="nav-item has-treeview">
            <a href="@Url.Action("Khuphong","Khuphong")" class="nav-link @ViewData["aKP"]">
                <i class="nav-icon fas fa-hotel"></i>
                <p>
                    Khu/Phòng
                </p>
            </a>
        </li>

        <!-- Hoadon -->
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link @ViewData["aHD"]">
                <i class="nav-icon fas fa-file-invoice-dollar"></i>
                <p>
                    Hóa đơn
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("Hoadonlephi","Hoadon")" class="nav-link @ViewData["aHDLP"]">
                        <p>Hóa đơn - Lệ phí</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Hoadondiennuoc","Hoadon")" class="nav-link @ViewData["aHDDN"]">
                        <p>Hóa đơn điện nước</p>
                    </a>
                </li>
            </ul>
        </li>

        <!-- QLVT -->
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link @ViewData["aQLVT"]">
                <i class="nav-icon fas fa-pallet"></i>
                <p>
                    Quản lý vật tư
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("Quanlykho","Quanlyvattu")" class="nav-link @ViewData["aQLK"]">
                        <p>Quản lý kho</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Tiepnhanyeucau","Quanlyvattu")" class="nav-link @ViewData["aTNYC"]">
                        <p>Tiếp nhận yêu cầu</p>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Yeu cau sua chua -->
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link @ViewData["aYCSC"]">
                <i class="nav-icon fas fa-tools"></i>
                <p>
                    Yêu cầu sửa chữa
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("Danhsachsuachua","Yeucausuachua")" class="nav-link @ViewData["aDSSC"]">
                        <p>Danh sách sửa chữa</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Chuyenyeucau","Yeucausuachua")" class="nav-link @ViewData["aCYC"]">
                        <p>Chuyển yêu cầu</p>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Quản lý giặt ủi -->
        <li class="nav-item has-treeview">
            <a href="@Url.Action("Danhsachgiatui","Quanlygiatui")" class="nav-link @ViewData["aQLGU"]">
                <i class="nav-icon fas fa-hands-wash"></i>
                <p>
                    Quản lý giặt ủi
                </p>
            </a>
        </li>

        <!-- Bao cao thong ke -->
        <li class="nav-item">
            <a href="@Url.Action("Baocaothongke","Baocaothongke")" class="nav-link @ViewData["aBCTC"]">
                <i class="nav-icon far fa-chart-bar"></i>
                <p>
                    Báo cáo thống kê
                </p>
            </a>
        </li>

        <!-- Content Management System -->
        <li class="nav-item">
            <a href="@Url.Action("Index","CMS")" class="nav-link @ViewData["aCMS"]">
                <i class="nav-icon fas fa-tools"></i>
                <p>
                    CMS
                </p>
            </a>
        </li>

        <!-- Dang xuat -->
        <li class="nav-item has-treeview">
            <a href="@Url.Action("Login","Account")" class="nav-link">
                <i class="nav-icon fas fa-sign-out-alt"></i>
                <p>
                    Đăng xuất
                </p>
            </a>
        </li>
    </ul>
</nav>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeSidebarSearch.cshtml
<form action="#" method="get" class="sidebar-form">
    <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Tìm kiếm...">
        <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div>
</form>

DormitoryWebProject/Views/Shared/PartialViews/HomePartial/_HomeSidebarUser.cshtml
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="~/assets/images/dashboard/user3-128x128.jpg" class="img-circle elevation-2 user-img-scale" alt="User" id="user-img">
    </div>
    <div class="info">
        <a href="#" class="d-block">
            Alexa Rospova<br> <span style="color: #F4841A">General Manager</span>
        </a>
    </div>
</div>